// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace StajProje.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20231224101739_staj")]
    partial class staj
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.RickResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AirDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Characters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Episode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RickResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirDate = "December 2, 2013",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:33.798Z",
                            Episode = "S01E01",
                            Name = "Pilot",
                            Url = "https://rickandmortyapi.com/api/episode/1"
                        },
                        new
                        {
                            Id = 2,
                            AirDate = "December 9, 2013",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:33.916Z",
                            Episode = "S01E02",
                            Name = "Lawnmower Dog",
                            Url = "https://rickandmortyapi.com/api/episode/2"
                        },
                        new
                        {
                            Id = 3,
                            AirDate = "December 16, 2013",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:34.022Z",
                            Episode = "S01E03",
                            Name = "Anatomy Park",
                            Url = "https://rickandmortyapi.com/api/episode/3"
                        },
                        new
                        {
                            Id = 4,
                            AirDate = "January 13, 2014",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:34.129Z",
                            Episode = "S01E04",
                            Name = "M. Night Shaym-Aliens!",
                            Url = "https://rickandmortyapi.com/api/episode/4"
                        },
                        new
                        {
                            Id = 5,
                            AirDate = "January 20, 2014",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:34.236Z",
                            Episode = "S01E05",
                            Name = "Meeseeks and Destroy",
                            Url = "https://rickandmortyapi.com/api/episode/5"
                        },
                        new
                        {
                            Id = 6,
                            AirDate = "January 27, 2014",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:34.339Z",
                            Episode = "S01E06",
                            Name = "Rick Potion #9",
                            Url = "https://rickandmortyapi.com/api/episode/6"
                        },
                        new
                        {
                            Id = 7,
                            AirDate = "March 10, 2014",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:34.441Z",
                            Episode = "S01E07",
                            Name = "Raising Gazorpazorp",
                            Url = "https://rickandmortyapi.com/api/episode/7"
                        },
                        new
                        {
                            Id = 8,
                            AirDate = "March 17, 2014",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:34.543Z",
                            Episode = "S01E08",
                            Name = "Rixty Minutes",
                            Url = "https://rickandmortyapi.com/api/episode/8"
                        },
                        new
                        {
                            Id = 9,
                            AirDate = "March 24, 2014",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:34.645Z",
                            Episode = "S01E09",
                            Name = "Something Ricked This Way Comes",
                            Url = "https://rickandmortyapi.com/api/episode/9"
                        },
                        new
                        {
                            Id = 10,
                            AirDate = "April 7, 2014",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:34.747Z",
                            Episode = "S01E10",
                            Name = "Close Rick-counters of the Rick Kind",
                            Url = "https://rickandmortyapi.com/api/episode/10"
                        },
                        new
                        {
                            Id = 11,
                            AirDate = "April 14, 2014",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:34.850Z",
                            Episode = "S01E11",
                            Name = "Ricksy Business",
                            Url = "https://rickandmortyapi.com/api/episode/11"
                        },
                        new
                        {
                            Id = 12,
                            AirDate = "July 26, 2015",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:34.953Z",
                            Episode = "S02E01",
                            Name = "A Rickle in Time",
                            Url = "https://rickandmortyapi.com/api/episode/12"
                        },
                        new
                        {
                            Id = 13,
                            AirDate = "August 2, 2015",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:35.055Z",
                            Episode = "S02E02",
                            Name = "Mortynight Run",
                            Url = "https://rickandmortyapi.com/api/episode/13"
                        },
                        new
                        {
                            Id = 14,
                            AirDate = "August 9, 2015",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:35.158Z",
                            Episode = "S02E03",
                            Name = "Auto Erotic Assimilation",
                            Url = "https://rickandmortyapi.com/api/episode/14"
                        },
                        new
                        {
                            Id = 15,
                            AirDate = "August 16, 2015",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:35.261Z",
                            Episode = "S02E04",
                            Name = "Total Rickall",
                            Url = "https://rickandmortyapi.com/api/episode/15"
                        },
                        new
                        {
                            Id = 16,
                            AirDate = "August 23, 2015",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:35.364Z",
                            Episode = "S02E05",
                            Name = "Get Schwifty",
                            Url = "https://rickandmortyapi.com/api/episode/16"
                        },
                        new
                        {
                            Id = 17,
                            AirDate = "August 30, 2015",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:35.467Z",
                            Episode = "S02E06",
                            Name = "The Ricks Must Be Crazy",
                            Url = "https://rickandmortyapi.com/api/episode/17"
                        },
                        new
                        {
                            Id = 18,
                            AirDate = "September 13, 2015",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:35.569Z",
                            Episode = "S02E07",
                            Name = "Big Trouble in Little Sanchez",
                            Url = "https://rickandmortyapi.com/api/episode/18"
                        },
                        new
                        {
                            Id = 19,
                            AirDate = "September 20, 2015",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:35.669Z",
                            Episode = "S02E08",
                            Name = "nterdimensional Cable 2: Tempting Fate",
                            Url = "https://rickandmortyapi.com/api/episode/19"
                        },
                        new
                        {
                            Id = 20,
                            AirDate = "September 27, 2015",
                            Characters = "https://rickandmortyapi.com/api/character/1",
                            Created = "2017-11-10T12:56:35.772Z",
                            Episode = "S02E09",
                            Name = "Look Who's Purging Now",
                            Url = "https://rickandmortyapi.com/api/episode/20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
